### ISSUE TITLE
Make configuration aware of current file language

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/vscode-gremlins#31]
Some characters are dangerous in some languages, but not at all in others.

For example, non breaking spaces are perfectly valid, and even sometimes required, in texts (in Markdown for example), but would be less welcome in other files.

So (with #24 also) instead of 

```json
"00a0": {
  "description": "non breaking space"
}
```

We could have

```json
"00a0": {
  "description": "non breaking space",
  "level": "warning"
},
"[markdown]": {
  "00a0": {
    "level": "info"
  }
}
```

Of maybe the "markdown" key is in a higher level, as in https://vscode.readthedocs.io/en/latest/getstarted/settings/#language-specific-editor-settings ?

I don't know how to deal with that.

**Comment by ctf0** [comment]
i think you can do something like
```
"[markdown]": {
  "gremlins.characters": {
    // add the chars thats should show up in markdown in here
  }
}
```

**Comment by nhoizey** [comment]
That's what I saw in https://vscode.readthedocs.io/en/latest/getstarted/settings/#language-specific-editor-settings indeed, thanks for confirmation.

I'll try it like that.

**Comment by TheSench** [comment]
I did some testing on this, it turns out it works (sort of).  There are a handful of caveats:

1. VSCode does not recognize extension-specific settings inside a [language] block, so it highlights the key in yellow and reports it as a warning.
2. Retrieving the language-specific values is clunky - to use markdown as an example, first you must get the "[markdown]" settings, which returns a map of all of the settings underneath it.  It does not group any `"gremlins.<something>"` settings into a "gremlins" object, so you must either require users to enter language-specific settings differently than they would generic ones, or you must loop through all of the keys in that language's settings and manually pull out any that start with `"gremlins."`.
3. When listening to settings changes, you can no longer simply check for `event.affectsConfiguration("gremlins")`, since changes inside a language block don't trigger this (they only "affect" `"[markdown]"`, for instance).
4. Tracking "global" state like diagnostics collections becomes a pain unless we start creating a separate one of those for each language.

**Comment by TheSench** [comment]
Examples of bullet 2:
Normal configuration:
```
"gremlins.showInProblemPane": true,
"[markdown]": {
    "gremlins.showInProblemPane": false
}
```
Requiring user to change how the do language-specific configuration:
```
```
"gremlins.showInProblemPane": true,
"[markdown]": {
    "gremlins": {
        "showInProblemPane": false
    }
}
```

**Comment by TheSench** [comment]
I figured out how to properly register configuration to be language-overridable, which gets around problems # 1 and 3.  I'll be putting up a PR within the next few days.

**Comment by TheSench** [comment]
I see you have the `Hacktoberfest` tag added to this issue.  Apparently you need to add a "hacktoberfest" topic to your repository to participate this year:
> Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by TheSench** [comment]
So to get proper language-specific configuration, we need to be passing in a context when we load our configuration (which means we may need to go back to loading it every time, or, at a minimum, every time we are processing a file with a new language).

**Comment by TheSench** [comment]
Additionally, when defining gremlins.characters overrides, VSCode _merges_ the object with other configurations (e.g. language-specific settings _merge_ with generic settings, which _merge_ with the defaults).  I'm doing some digging to see if that behavior can be changed, but I understand that users may have already become aware and may be configuring based on this, so adjusting that behavior could be a breaking change for them (i.e. they may expect the defaults to always be there and may just be overriding certain characters).
